### ISSUE TITLE
questa è una issue sul frontend

### ISSUE THREAD

**Issue by loredanaribatto** [PulitaZube/frontrepo#1]

**Comment by debrando** [comment]
Io metterei anche label e milestone, ma non ne ho diritto >.<

**Comment by debrando** [comment]
Per caso non è che manchino label e milestone, e che solo io non abbia il dirtito di crearle?

**Comment by debrando** [comment]
### BORIBOMBO

**Comment by debrando** [comment]
HO FINITO, OLE'!
